#!/bin/bash
echo "=== Build Environment Debug ==="
echo "Current directory: $(pwd)"
echo "Node version: $(node --version)"
echo "NPM version: $(npm --version)"
echo ""
echo "=== Directory structure ==="
ls -la
echo ""
echo "=== src directory ==="
ls -la src/ || echo "src directory not found"
echo ""
echo "=== vite.config.ts location ==="
ls -la vite.config.ts || echo "vite.config.ts not found"
echo ""
echo "=== tsconfig.json content ==="
cat tsconfig.json || echo "tsconfig.json not found"
echo ""
echo "=== Running vite build ==="
vite build
